server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html login.html; # instrucción para iniciar con la pagina de información.

    location / {
        # Cambio: se redirige el fallback a index.html (página inicial) para mostrar el landing.
        try_files $uri $uri/ /index.html;
    }

    # Proxy hacia la API en la red interna de Docker.
    location /api/ {
        proxy_pass http://api:8080/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
